"""Install, start, stop and observe hosted applications.

The supervisor is the *parent* in the isolation design: it creates the listening
unix socket, hands the descriptor to the confined app, and serves as the only
thing that can reach it. The app therefore never calls ``socket()``/``bind()``
and those syscalls are denied to it.

Processes are tracked in memory and reconciled against the database, so a
crashed app is reported as ``error`` rather than staying "running" forever.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import shutil
import signal
import socket
import subprocess
import sys
import threading
import time
import threading
import time
from pathlib import Path

from src.hosting import applog, archive, capabilities, environment, instances, settings
from src.hosting.errors import HostingError
from src.hosting.paths import (
    app_root, code_dir, install_log_path, interpreter, log_path, report_path,
    run_dir, socket_path, venv_dir,
)
from src.hosting.instances import INSTANCE_TOKEN
from src.models.hosted_app import HostedApp, HostedAppStatus


READY_TIMEOUT_SECONDS = 45
STOP_GRACE_SECONDS = 5
_LOG_LOCK = threading.Lock()
_PROCESSES: dict[str, subprocess.Popen] = {}


# --- paths ----------------------------------------------------------------

def app_root(slug: str) -> Path:
    return settings.root() / slug


def code_dir(slug: str) -> Path:
    return app_root(slug) / "app"


def venv_dir(slug: str) -> Path:
    return app_root(slug) / "venv"


def run_dir(slug: str) -> Path:
    return app_root(slug) / "run"


def install_log_path(slug: str) -> Path:
    return app_root(slug) / "logs" / "install.log"


def log_path(slug: str) -> Path:
    return app_root(slug) / "logs" / "app.log"


def report_path(slug: str) -> Path:
    return app_root(slug) / "runtime.json"


def socket_path(slug: str) -> Path:
    """A short, fixed-length socket path.

    AF_UNIX limits a socket path to about 108 bytes, and a long slug under the
    default root would silently exceed it. The app never sees this path - it
    inherits the descriptor - so it can be derived from a hash instead.
    """
    digest = hashlib.sha1(slug.encode("utf-8")).hexdigest()[:16]
    return settings.root() / ".sockets" / f"{digest}.sock"


def interpreter(slug: str) -> str:
    """The venv interpreter when one exists, else the platform interpreter."""
    candidate = venv_dir(slug) / "bin" / "python"
    return str(candidate) if candidate.exists() else settings.python_executable()


# --- install --------------------------------------------------------------

HOST_WRAPPER = "_host_wsgi.py"


def _write_host_wrapper(slug: str, entry: str) -> str:
    """Generate the wrapper gunicorn loads, and return its entry point.

    An externally built app knows nothing about being mounted under a prefix, so
    ``url_for`` would emit ``/static/...`` and every asset would 404. ProxyFix
    turns the ``X-Forwarded-Prefix`` header the platform already sends into
    ``SCRIPT_NAME``, which makes the app generate correct URLs itself - no
    rewriting of its HTML, and no cooperation required from its author.
    """
    module, _, attribute = entry.partition(":")
    source = (
        '"""Generated by the platform. Do not edit: rewritten on every start."""\n'
        "from werkzeug.middleware.proxy_fix import ProxyFix\n"
        f"from {module} import {attribute} as _app\n\n"
        "application = ProxyFix(_app, x_prefix=1)\n"
    )
    (code_dir(slug) / HOST_WRAPPER).write_text(source)
    return f"{HOST_WRAPPER[:-3]}:application"


def _gunicorn_command(slug: str, fd: int, workers: int, entry: str) -> list[str]:
    return [
        interpreter(slug), "-m", "gunicorn",
        "--bind", f"fd://{fd}",
        # gunicorn 25 creates its own control socket by default, which needs
        # socket()+bind(); both are denied to the app.
        "--no-control-socket",
        "--chdir", str(code_dir(slug)),
        "--workers", str(max(1, workers)),
        # "info" so the log shows startup, worker and shutdown lines. Access
        # logging stays off: the platform's audit trail already records every
        # request, and duplicating it here would only bloat the file.
        "--log-level", "info",
        entry,
    ]


def _worker_count(record) -> int:
    """Gunicorn worker count from the manifest, clamped to something sane."""
    try:
        workers = int(record.manifest.get("workers") or 1)
    except (TypeError, ValueError):
        workers = 1
    return max(1, min(workers, 8))


def _listening_socket(slug: str) -> tuple[socket.socket, int]:
    path = socket_path(slug)
    path.parent.mkdir(parents=True, exist_ok=True)
    os.chmod(path.parent, 0o700)
    if path.exists():
        path.unlink()
    listener = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    listener.bind(str(path))
    os.chmod(path, 0o600)          # the parent is the only intended client
    listener.listen(64)
    return listener, listener.fileno()


def start(slug: str, *, tier: str | None = None) -> tuple[bool, str]:
    """Launch the app under the configured (or best available) tier."""
    record = HostedApp.get_by_slug(slug)
    if record is None:
        return False, f"'{slug}' is not installed"
    if _process_for(slug) is not None:
        return True, "already running"
    if not code_dir(slug).is_dir():
        message = (
            f"The files for '{slug}' are missing from its workspace, so it cannot be started. "
            "Import the application again, or remove this entry."
        )
        HostedApp.set_runtime(slug, status=HostedAppStatus.ERROR, last_error=message)
        return False, message

    caps = capabilities.detect()
    selected, reason = capabilities.resolve_tier(caps, tier or settings.configured_tier())
    if selected is None:
        HostedApp.set_runtime(slug, status=HostedAppStatus.ERROR, last_error=reason)
        return False, reason

    try:
        listener, fd = _listening_socket(slug)
    except OSError as exc:
        message = (
            f"could not create the app socket: {exc}. A unix socket path is limited to "
            f"about 108 bytes; this one is {len(str(socket_path(slug)))}."
        )
        HostedApp.set_runtime(slug, status=HostedAppStatus.ERROR, last_error=message)
        return False, message
    workers = _worker_count(record)
    try:
        wrapped_entry = _write_host_wrapper(slug, record.entry)
    except OSError as exc:
        listener.close()
        return False, f"could not prepare the app wrapper: {exc}"
    command = _gunicorn_command(slug, fd, workers, wrapped_entry)
    launcher = [
        settings.python_executable(), "-m", "src.hosting.launcher",
        "--app-dir", str(app_root(slug)),
        "--venv-dir", str(venv_dir(slug)),
        "--tier", tier or settings.configured_tier(),
        "--socket-fd", str(fd),
        "--report", str(report_path(slug)),
        "--",
        *command,
    ]

    applog.rotate(log_path(slug))
    applog.banner(log_path(slug), slug=slug, tier=selected, reason=reason,
                  isolated=selected in ("A", "B+"), command=command)
    log = open(log_path(slug), "ab", buffering=0)
    try:
        proc = subprocess.Popen(
            launcher,
            cwd=str(settings.platform_root()),
            stdout=log,
            stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
            pass_fds=(fd,),
            start_new_session=True,   # so the whole group can be stopped later
        )
    except Exception as exc:
        listener.close()
        log.close()
        HostedApp.set_runtime(slug, status=HostedAppStatus.ERROR, last_error=str(exc))
        return False, f"could not launch: {exc}"

    ready, detail = _wait_until_ready(slug, proc)
    if not ready:
        _terminate(proc)
        listener.close()
        log.close()
        message = detail or "the app did not answer within the startup window"
        HostedApp.set_runtime(slug, status=HostedAppStatus.ERROR, last_error=message)
        return False, message

    report = _read_report(slug)
    _PROCESSES[slug] = proc
    _audit_start(slug, record, report.get("tier", selected), report.get("tier_reason", reason),
                 report.get("filesystem_isolated", selected in ("A", "B+")))
    HostedApp.set_runtime(
        slug,
        status=HostedAppStatus.RUNNING,
        pid=proc.pid,
        tier=report.get("tier", selected),
        tier_reason=report.get("tier_reason", reason),
        filesystem_isolated=report.get("filesystem_isolated", selected in ("A", "B+")),
        last_error="",
        owner=INSTANCE_TOKEN,
        desired_state="running",
        mark_started=True,
    )
    return True, f"running under tier {report.get('tier', selected)}"


def stop(slug: str, *, intentional: bool = True) -> tuple[bool, str]:
    """Stop an app.

    ``intentional`` distinguishes "the operator asked for this" from "the
    platform is shutting down". Only the former changes the desired state, so a
    restart brings back exactly the apps that were running.
    """
    desired = "stopped" if intentional else None
    proc = _process_for(slug)
    if proc is None:
        # Not in our registry, but the database may still point at a process
        # left behind by an earlier platform run.
        record = HostedApp.get_by_slug(slug)
        if record is not None and record.pid and _looks_like_our_app(record.pid, slug):
            try:
                os.killpg(os.getpgid(record.pid), signal.SIGKILL)
            except OSError:
                pass
        HostedApp.set_runtime(slug, status=HostedAppStatus.STOPPED, desired_state=desired)
        return True, "not running"
    _terminate(proc)
    _PROCESSES.pop(slug, None)
    HostedApp.set_runtime(slug, status=HostedAppStatus.STOPPED, desired_state=desired)
    return True, "stopped"


def restart(slug: str, *, tier: str | None = None) -> tuple[bool, str]:
    stop(slug)
    return start(slug, tier=tier)


def uninstall(slug: str) -> tuple[bool, str]:
    stop(slug)
    root = app_root(slug)
    if root.exists():
        shutil.rmtree(root, ignore_errors=True)
    try:
        socket_path(slug).unlink()
    except OSError:
        pass
    HostedApp.delete(slug)
    return True, "removed"


def _audit_start(slug: str, record, tier: str, reason: str, isolated: bool) -> None:
    """Record which isolation actually confined this app, in the audit trail.

    The request that asked for the start is audited by the middleware; this adds
    the part that only the supervisor knows - the tier that was applied - so
    "which of our hosted apps are genuinely isolated?" is answerable from the
    audit log alone.
    """
    try:
        from src.auth import audit

        # start() normally runs inside the request that asked for it, so the
        # event can be attributed to the administrator who triggered it.
        ip = username = None
        try:
            from flask import has_request_context, request, session

            if has_request_context():
                ip = request.remote_addr
                username = session.get("username")
        except Exception:
            pass

        audit.record(
            status=audit.STATUS_SUCCESS,
            endpoint=f"POST /apps/{slug}/start",
            ip=ip,
            username=username,
            comment=audit.build_comment(
                "hosted app start",
                module="hosted_apps",
                level="write",
                target=(
                    f"slug={slug} tier={tier} filesystem_isolated={isolated} "
                    f"network_isolated={report_network_isolated()} "
                    f"sandbox_report={report_path(slug)}"
                ),
                reason=reason or None,
                http_status=200,
            ),
        )
    except Exception:  # auditing must never prevent an app from starting
        pass


def report_network_isolated() -> bool:
    try:
        return bool(capabilities.detect().get("network_isolated"))
    except Exception:
        return False


def _terminate(proc: subprocess.Popen) -> None:
    """Stop the app's whole process group.

    When signals are denied (the default) there is no point sending SIGTERM
    first: the app cannot act on it. Gunicorn's arbiter would try to signal its
    own workers, fail with EPERM, and write a misleading traceback into the
    app's log. SIGKILL goes straight to the group instead, which is what
    actually stops it. An app that opted into signals
    (``HOSTED_APPS_ALLOW_SIGNALS=true``) gets the graceful path.
    """
    try:
        group = os.getpgid(proc.pid)
    except OSError:
        return
    attempts = (signal.SIGTERM, signal.SIGKILL) if settings.allow_signals() else (signal.SIGKILL,)
    for sig in attempts:
        try:
            os.killpg(group, sig)
        except OSError:
            break
        try:
            proc.wait(timeout=STOP_GRACE_SECONDS)
            return
        except subprocess.TimeoutExpired:
            continue


def _process_for(slug: str) -> subprocess.Popen | None:
    proc = _PROCESSES.get(slug)
    if proc is not None and proc.poll() is not None:
        _PROCESSES.pop(slug, None)
        return None
    return proc


def _wait_until_ready(slug: str, proc: subprocess.Popen) -> tuple[bool, str]:
    """The socket exists the moment *we* create it, so readiness must be a real
    request - a successful connect only proves the backlog accepted it."""
    import httpx

    path = str(socket_path(slug))
    deadline = time.time() + READY_TIMEOUT_SECONDS
    last = ""
    while time.time() < deadline:
        if proc.poll() is not None:
            return False, applog.tail(log_path(slug), 40) or f"the app exited with code {proc.returncode}"
        client = httpx.Client(transport=httpx.HTTPTransport(uds=path), base_url="http://app", timeout=3)
        try:
            client.get("/", follow_redirects=False)
            return True, ""
        except Exception as exc:
            last = f"{type(exc).__name__}: {exc}"
            time.sleep(0.4)
        finally:
            client.close()
    return False, f"no response within {READY_TIMEOUT_SECONDS}s ({last})"


# --- observation ----------------------------------------------------------

def _read_report(slug: str) -> dict:
    try:
        return json.loads(report_path(slug).read_text())
    except (OSError, json.JSONDecodeError):
        return {}


def logs(slug: str, lines: int = 200, source: str = "app") -> str:
    """Tail the app's own log, or the install log when ``source='install'``.

    Newest line first. The reason to open a log is the last thing that
    happened, so the tail is handed over in the order it is read - the way
    ``tail -r`` and ``journalctl -r`` do it - rather than making every reader
    scroll to the bottom of the box to find the line they came for.
    """
    path = install_log_path(slug) if source == "install" else log_path(slug)
    tail = applog.tail(path, lines).splitlines()
    while tail and not tail[-1].strip():
        tail.pop()  # a log that ends in a blank line must not begin with one
    return "\n".join(reversed(tail))


def get_status(slug: str) -> str:
    """Live status, not the stored one: a dead process is never "running".

    A row can say ``running`` after a platform restart, or after an app died
    without the supervisor noticing. Trusting it would send the proxy after a
    stale socket and answer 502 when the honest answer is 503.
    """
    if _process_for(slug) is not None:
        return HostedAppStatus.RUNNING
    record = HostedApp.get_by_slug(slug)
    if record is None:
        return HostedAppStatus.STOPPED
    if record.status == HostedAppStatus.RUNNING and record.pid:
        if record.owner and record.owner != INSTANCE_TOKEN and instances.instance_alive(record.owner):
            return HostedAppStatus.RUNNING  # another live platform instance runs it
        if not _looks_like_our_app(record.pid, slug):
            return HostedAppStatus.STOPPED
    return record.status


def _looks_like_our_app(pid: int, slug: str) -> bool:
    """Whether ``pid`` is the hosted app ``slug`` (see ``instances``)."""
    return instances.process_is_app(pid, str(app_root(slug)))


def reap_orphans() -> list[tuple[str, str]]:
    """Stop apps left running by a platform instance that is gone.

    A hosted app is deliberately started in its own session so a platform
    restart cannot take it down by accident. The cost is that an unclean exit
    (SIGKILL, a crash) can leave one running: unreachable, because the socket is
    recreated on the next start, but still consuming resources.
    """
    reaped: list[tuple[str, str]] = []
    for record in HostedApp.get_all():
        if record.status != HostedAppStatus.RUNNING or not record.pid:
            continue
        if record.owner == INSTANCE_TOKEN:
            continue  # ours; the in-memory registry is authoritative
        if record.owner and instances.instance_alive(record.owner):
            continue  # another live platform instance owns it
        if not _looks_like_our_app(record.pid, record.slug):
            HostedApp.set_runtime(record.slug, status=HostedAppStatus.STOPPED)
            continue
        try:
            os.killpg(os.getpgid(record.pid), signal.SIGKILL)
            reaped.append((record.slug, f"reaped orphaned process {record.pid}"))
        except OSError as exc:
            reaped.append((record.slug, f"could not reap {record.pid}: {exc}"))
        HostedApp.set_runtime(record.slug, status=HostedAppStatus.STOPPED)
    return reaped


def reconcile() -> None:
    """Refresh stored state for the apps this instance runs.

    Apps owned by another live instance are left alone: their status is that
    instance's business, and clobbering it would show a running app as failed.
    """
    for record in HostedApp.get_all():
        if record.owner and record.owner != INSTANCE_TOKEN and instances.instance_alive(record.owner):
            continue
        if record.status != HostedAppStatus.INSTALLING and not code_dir(record.slug).is_dir():
            if record.status != HostedAppStatus.ERROR:
                HostedApp.set_runtime(
                    slug=record.slug, status=HostedAppStatus.ERROR,
                    last_error="The application's files are missing from its workspace. Import it again.",
                )
            continue
        running = _process_for(record.slug) is not None
        if running and record.status != HostedAppStatus.RUNNING:
            HostedApp.set_runtime(record.slug, status=HostedAppStatus.RUNNING)
        elif not running and record.status == HostedAppStatus.RUNNING:
            HostedApp.set_runtime(
                record.slug, status=HostedAppStatus.ERROR,
                last_error=record.last_error or "the process is no longer running",
            )


def autostart_all(on_result=None) -> list[str]:
    """Bring back the apps that should be running, each in its own thread.

    Two things bring an app back at boot: the operator left it running, or its
    manifest asks to autostart. The operator's instruction outranks the
    manifest's preference - an app they stopped stays stopped. So ``autostart``
    only decides the apps the operator has not ruled on: a freshly imported one,
    whose ``desired_state`` is still empty. Remembering the operator's choice is
    what makes a platform restart invisible.

    The starts happen in the background on purpose. A hosted app that hangs on
    startup must never hold up the platform's own boot, and there is no reason
    for the second app to wait for the first. Returns the slugs being started.
    """
    slugs: list[str] = []
    for record in HostedApp.get_all():
        if record.status == HostedAppStatus.ERROR:
            continue  # a broken app should not be retried blindly at every boot
        if record.desired_state == "stopped":
            continue  # the operator stopped it; that is the last word
        if not record.autostart and record.desired_state != "running":
            continue
        if not code_dir(record.slug).is_dir():
            if on_result:
                on_result(record.slug, False, "the application's files are missing")
            continue
        slugs.append(record.slug)

    def run(slug: str) -> None:
        try:
            ok, message = start(slug)
        except Exception as exc:  # pragma: no cover - defensive
            ok, message = False, str(exc)
        if on_result:
            on_result(slug, ok, message)

    for slug in slugs:
        threading.Thread(target=run, args=(slug,), name=f"autostart-{slug}", daemon=True).start()
    return slugs


def shutdown_all() -> None:
    """Stop every app we run, without forgetting that they were meant to run."""
    with _LOG_LOCK:
        for slug in list(_PROCESSES):
            try:
                stop(slug, intentional=False)
            except Exception:  # pragma: no cover - shutdown must not raise
                continue
