"""WSGI wrapper and command generation for hosted applications.

Kept apart from supervisor so WSGI generation and Gunicorn command line building
remain decoupled from process supervision.
"""

from __future__ import annotations

from typing import Any
from src.hosting.paths import code_dir, interpreter

HOST_WRAPPER = "_host_wsgi.py"


def write_host_wrapper(slug: str, entry: str) -> str:
    """Generate the wrapper gunicorn loads, and return its entry point.

    An externally built app knows nothing about being mounted under a prefix, so
    ``url_for`` would emit ``/static/...`` and every asset would 404. ProxyFix
    turns the ``X-Forwarded-Prefix`` header the platform already sends into
    ``SCRIPT_NAME``, which makes the app generate correct URLs itself - no
    rewriting of its HTML, and no cooperation required from its author.
    """
    module, _, attribute = entry.partition(":")
    source = (
        '"""Generated by the platform. Do not edit: rewritten on every start."""\n'
        "from werkzeug.middleware.proxy_fix import ProxyFix\n"
        f"from {module} import {attribute} as _app\n\n"
        "application = ProxyFix(_app, x_prefix=1)\n"
    )
    (code_dir(slug) / HOST_WRAPPER).write_text(source)
    return f"{HOST_WRAPPER[:-3]}:application"


def build_gunicorn_command(slug: str, fd: int, workers: int, entry: str) -> list[str]:
    return [
        interpreter(slug), "-m", "gunicorn",
        "--bind", f"fd://{fd}",
        # gunicorn 25 creates its own control socket by default, which needs
        # socket()+bind(); both are denied to the app.
        "--no-control-socket",
        "--chdir", str(code_dir(slug)),
        "--workers", str(max(1, workers)),
        # "info" so the log shows startup, worker and shutdown lines. Access
        # logging stays off: the platform's audit trail already records every
        # request, and duplicating it here would only bloat the file.
        "--log-level", "info",
        entry,
    ]


def get_worker_count(record: Any) -> int:
    """Gunicorn worker count from the manifest, clamped to something sane."""
    try:
        workers = int(record.manifest.get("workers") or 1)
    except (TypeError, ValueError, AttributeError):
        workers = 1
    return max(1, min(workers, 8))
